### ISSUE TITLE
Please specify package version

### ISSUE THREAD

**Issue by newuhe** [cadop/nodeik#16]
There are several problems when using train script after pip installation. The version of urdpy,pycollada,numpy and so on do affect where the train script can run. Or provide an envrioemnt.yaml or docker.
And when i run train_from_panda_urdf.py, it throws:

>   warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
> Warp CUDA error: Failed to get function cuGetProcAddress
> Warp 0.10.1 initialized:
>    CUDA devices not available
>    Devices:
>      "cpu"    | x86_64
>    Kernel cache: /home/junfeng/.cache/warp/0.10.1
> Traceback (most recent call last):
>   File "/home/junfeng/.local/lib/python3.8/site-packages/collada/__init__.py", line 201, in __init__
>     self.xmlnode = ElementTree.ElementTree(element=None,
>   File "src/lxml/etree.pyx", line 3175, in lxml.etree.ElementTree
>   File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseDocument
>   File "src/lxml/parser.pxi", line 1916, in lxml.etree._parseMemoryDocument
>   File "src/lxml/parser.pxi", line 1803, in lxml.etree._parseDoc
>   File "src/lxml/parser.pxi", line 1144, in lxml.etree._BaseParser._parseDoc
>   File "src/lxml/parser.pxi", line 618, in lxml.etree._ParserContext._handleParseResultDoc
>   File "src/lxml/parser.pxi", line 728, in lxml.etree._handleParseResult
>   File "src/lxml/parser.pxi", line 657, in lxml.etree._raiseParseError
>   File "<string>", line 1
> lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "examples/train_from_panda_urdf.py", line 84, in <module>
>     run()
>   File "examples/train_from_panda_urdf.py", line 60, in run
>     r, dataloader, val_dataloader = get_robot(filepath)
>   File "examples/train_from_panda_urdf.py", line 43, in get_robot
>     r = Robot(robot_path=filepath, ee_link_name='panda_hand')
>   File "/home/junfeng/nodeik/nodeik/robots/robot.py", line 18, in __init__
>     self.link_index = parse_urdf(
>   File "/home/junfeng/nodeik/nodeik/warp/urdf_loader.py", line 126, in parse_urdf
>     robot = urdfpy.URDF.load(filename)
>   File "/home/junfeng/.local/lib/python3.8/site-packages/urdfpy/urdf.py", line 3729, in load
>     return URDF._from_xml(node, path)
>   File "/home/junfeng/.local/lib/python3.8/site-packages/urdfpy/urdf.py", line 3926, in _from_xml
>     kwargs = cls._parse(node, path)
>   File "/home/junfeng/.local/lib/python3.8/site-packages/urdfpy/urdf.py", line 161, in _parse
>     kwargs.update(cls._parse_simple_elements(node, path))
>   File "/home/junfeng/.local/lib/python3.8/site-packages/urdfpy/urdf.py", line 137, in _parse_simple_elements
>     v = [t._from_xml(n, path) for n in vs]
>   File "/home/junfeng/.local/lib/python3.8/site-packages/urdfpy/urdf.py", line 137, in <listcomp>
>     v = [t._from_xml(n, path) for n in vs]
>   File "/home/junfeng/.local/lib/python3.8/site-packages/urdfpy/urdf.py", line 181, in _from_xml
>     return cls(**cls._parse(node, path))
>   File "/home/junfeng/.local/lib/python3.8/site-packages/urdfpy/urdf.py", line 161, in _parse
>     kwargs.update(cls._parse_simple_elements(node, path))
>   File "/home/junfeng/.local/lib/python3.8/site-packages/urdfpy/urdf.py", line 137, in _parse_simple_elements
>     v = [t._from_xml(n, path) for n in vs]
>   File "/home/junfeng/.local/lib/python3.8/site-packages/urdfpy/urdf.py", line 137, in <listcomp>
>     v = [t._from_xml(n, path) for n in vs]
>   File "/home/junfeng/.local/lib/python3.8/site-packages/urdfpy/urdf.py", line 1146, in _from_xml
>     kwargs = cls._parse(node, path)
>   File "/home/junfeng/.local/lib/python3.8/site-packages/urdfpy/urdf.py", line 161, in _parse
>     kwargs.update(cls._parse_simple_elements(node, path))
>   File "/home/junfeng/.local/lib/python3.8/site-packages/urdfpy/urdf.py", line 127, in _parse_simple_elements
>     v = t._from_xml(v, path)
>   File "/home/junfeng/.local/lib/python3.8/site-packages/urdfpy/urdf.py", line 181, in _from_xml
>     return cls(**cls._parse(node, path))
>   File "/home/junfeng/.local/lib/python3.8/site-packages/urdfpy/urdf.py", line 161, in _parse
>     kwargs.update(cls._parse_simple_elements(node, path))
>   File "/home/junfeng/.local/lib/python3.8/site-packages/urdfpy/urdf.py", line 127, in _parse_simple_elements
>     v = t._from_xml(v, path)
>   File "/home/junfeng/.local/lib/python3.8/site-packages/urdfpy/urdf.py", line 581, in _from_xml
>     meshes = load_meshes(fn)
>   File "/home/junfeng/.local/lib/python3.8/site-packages/urdfpy/utils.py", line 225, in load_meshes
>     meshes = trimesh.load(filename)
>   File "/home/junfeng/.local/lib/python3.8/site-packages/trimesh/exchange/load.py", line 120, in load
>     loaded = load_mesh(file_obj, file_type=file_type, resolver=resolver, **kwargs)
>   File "/home/junfeng/.local/lib/python3.8/site-packages/trimesh/exchange/load.py", line 191, in load_mesh
>     results = loader(file_obj, file_type=file_type, resolver=resolver, **kwargs)
>   File "/home/junfeng/.local/lib/python3.8/site-packages/trimesh/exchange/dae.py", line 52, in load_collada
>     c = collada.Collada(file_obj, ignore=ignores)
>   File "/home/junfeng/.local/lib/python3.8/site-packages/collada/__init__.py", line 204, in __init__
>     raise DaeMalformedError("XML Parsing Error: %s" % e)
> collada.common.DaeMalformedError: DaeMalformedError: XML Parsing Error: Start tag expected, '<' not found, line 1, column 1 (<string>, line 1)

my pycollada version is 0.6, urdfpy version is 0.0.22, lxml version is 4.9.3

**Comment by cadop** [comment]
Thanks for opening the issue. From the first few lines of your error, you do not have a GPU which is needed for training. 

I'll add some version numbers in case there are other issues, but please try to resolve the first one and let me know if it works.

**Comment by cadop** [comment]
I looked into this more. Your error is not from a package version, its that you don't have gitlfs installed. So when you pulled the repo, the dae files are just gitlfs pointers.  

Install gitlfs, then `git lfs fetch`


There were separately some breaking changes to packages, so this versions should work instead:

```
numpy==1.22.3
warp-lang==0.2.3
pytorch_lightning==1.5.10
```

**Comment by newuhe** [comment]
> I looked into this more. Your error is not from a package version, its that you don't have gitlfs installed. So when you pulled the repo, the dae files are just gitlfs pointers.
> 
> Install gitlfs, then `git lfs fetch`
> 
> There were separately some breaking changes to packages, so this versions should work instead:
> 
> ```
> numpy==1.22.3
> warp-lang==0.2.3
> pytorch_lightning==1.5.10
> ```

Thanks for replying. My problem is solved.
